### ISSUE TITLE
Error adding entities for domain device_tracker with platform google_maps

### ISSUE THREAD

**Issue by rozhkovets** [pnbruckner/ha-google-maps#17]
HA 2023.10.5
old but still compatible, I wouldn't want to upgrade

ha-google-maps 1.1.0

I have an account with which I share the location of 2 other accounts (if I understand correctly, this is an alternative account)

I created a cookies file in chrome and added to integration with default settings, and got this.
```

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 616, in _async_add_entity
    device = dev_reg.async_get(self.hass).async_get_or_create(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: DeviceRegistry.async_get_or_create() got an unexpected keyword argument 'serial_number'
```

```
Error while setting up google_maps platform for device_tracker
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 367, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 616, in _async_add_entity
    device = dev_reg.async_get(self.hass).async_get_or_create(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: DeviceRegistry.async_get_or_create() got an unexpected keyword argument 'serial_number'

```

**Comment by rozhkovets** [comment]
> I'm not sure what you mean by that comment. Can you elaborate?

do not pay attention.  I plan to stay on this version of HA for as long as I can.  I understand that the update may help avoid some errors, but may also introduce new errors with my other components

**Comment by pnbruckner** [comment]
Ok, thanks, I understand.

This one is a little more difficult to fix for HA versions older than 2023.11.0, but I think I can do it. Stay tuned. I'll hopefully release a fix soon.

**Comment by pnbruckner** [comment]
Discovered that the error does not occur with very new HA versions, but also doesn't occur with 2023.7.0 (which is the earliest version that I know works with this custom integration.) So the problem only happens with versions between those extremes. Hmm, doesn't make testing very easy.

Anyway, I found a fix and will be releasing it soon.

**Comment by pnbruckner** [comment]
@rozhkovets please let me know if 1.1.1 resolves the problem for you.

**Comment by rozhkovets** [comment]
@pnbruckner, it works, thank you
