### ISSUE TITLE
person_data[1] may be None

### ISSUE THREAD

**Issue by pnbruckner** [pnbruckner/ha-google-maps#20]
person_data[1] normally contains location data, but apparently, sometimes its value can be None (even though other elements, such as person_data[6], which contains full name, nickname, etc. are present.)

Since code currently expects person_data[1] to be valid whenever _any_ data for shared person is present, decide how to handle this scenario (i.e., misc_data present, but not loc_data.) Currently this causes an ERROR. Just ignore it? Use it, but allow location fields to be None? ...?

**Comment by Failure404** [comment]
Hi,
yes I seem to be suffering from this. I have one person sharing his location with me, but most of the time that person is offline and no location data is available. Now, with 1.2.0b0 the integration refuses to work because of this.

**Comment by pnbruckner** [comment]
Actually, in your case of a single shared account, it wouldn't make a difference, other than how the situation is reported. Either this new beta, or the older version, would effectively stop updating the tracker entity when this happens. Well, I guess that's only true if you're NOT using the account holder entity, too. If you are, then yes, this bug would prevent the account holder entity from updating.

I definitely plan to fix this today if at all possible.

**Comment by pnbruckner** [comment]
Fixed in 1.2.0b1. Works as before; i.e., the tracker entity for the person missing location data is not updated, and a message is written to the log, instead of failing the entire update.
