### ISSUE TITLE
Authentication expired for <user>@gmail.com

### ISSUE THREAD

**Issue by gpion** [pnbruckner/ha-google-maps#22]
I'm getting repeated _"Authentication expired"_ errors
![image](https://github.com/pnbruckner/ha-google-maps/assets/2971216/66c3e98d-0509-4554-8370-e8505f65bdbb)

Reloading the *same* cookie file produce _"Invalid cookies file"_ error

Only solution found so far is to restart the procedure from scratch but sooner or later the error comes back.

**Comment by pnbruckner** [comment]
Please read the following and let me know if it helps:

https://community.home-assistant.io/t/enhanced-google-maps-integration/682993/55

**Comment by gpion** [comment]
I had skipped the following step :

_"Go to Security → “Manage all device” (under “Your devices”). All currently signed in sessions (including the one you just started) should be listed. Click on, and sign-out of, all of those sessions. You won’t, of course, be able to sign-out of the current session (probably listed at the top) this way."_

I'm going to try this approach and see if it works

**Comment by gpion** [comment]
Something I don't understand.

In the readme there is this warning  (which I had strictly observed)
_"It is extremely important to NOT log out from Google in the browser you use to get the cookies file. "_

but in the [forum post](https://community.home-assistant.io/t/enhanced-google-maps-integration/682993/55)
_"Now sign-out of the current session "_

What is the difference between "log out" ans "sign out" ?

**Comment by pnbruckner** [comment]
Those are two different procedures. And sign out & log out are just two different terms for the same thing.

In the forum post it's explaining how to make sure all other sessions are logged out. In this procedure you should log out when you're done.

In the readme (and the procedures in the actual config flow) it's explaining how to grab the cookies file. In this procedure you should NOT log out, but should rather close the browser window.

**Comment by pnbruckner** [comment]
@gpion were you able to get it to work? If not, could you enable debug for the custom component, and then check the log for any messages near and/or related to the error?

**Comment by gpion** [comment]
> @gpion were you able to get it to work? 

Connection has been stable since reconfiguration
Fingers crossed
