### ISSUE TITLE
Blank Config fields

### ISSUE THREAD

**Issue by PMizz13** [pnbruckner/ha-google-maps#23]
When I try to install this I get presented with a blank field. IfI put something in it and click next I get 3 more blanks with arrows. I think the text prompts are missing?

**Comment by pnbruckner** [comment]
What method did you use to install it? What HA core version are you using? What version of this integration are you using? Were there any ERROR or WARNING messages in the log?

From the symptoms you describe, it sounds like maybe you need to force refresh your browser (e.g., Ctrl-F5, or whatever is appropriate for the browser you are using.)

**Comment by pnbruckner** [comment]
@PMizz13 I'm closing due to lack of response. Feel free to reopen if necessary.
