### ISSUE TITLE
Can App Passwords be used instead?

### ISSUE THREAD

**Issue by rcmaehl** [pnbruckner/ha-google-maps#31]
https://support.google.com/accounts/answer/185833?hl=en

Would probably be more reliable than cookies and doesn't require 2FA setup

**Comment by pnbruckner** [comment]
Honestly, I wouldn't know how to use it. I.e., I wouldn't know how to "log in".

**Comment by pnbruckner** [comment]
Closing because I have no idea how to use this suggestion. Feel free to reopen with more info/details about how this might work.

**Comment by rcmaehl** [comment]
> Honestly, I wouldn't know how to use it. I.e., I wouldn't know how to "log in".

Should just be the standard login process for an account, just use the app password instead of the account password

**Comment by pnbruckner** [comment]
The point is, this integration doesn't "log in" to the Google servers. It uses a cookies file from a web browser's session. The web browser does the logging in, and this integration just pretends to "be" that web browser session. It has no code to initiate any kind of logging in process.
