### ISSUE TITLE
Version 1.3.2 - unable to reconfigure via home assistant

### ISSUE THREAD

**Issue by ntbritton** [pnbruckner/ha-google-maps#33]
When i choose reconfigure in HA i get the following message:

Config flow could not be loaded: 500 Internal Server Error Server got itself in trouble

I went through the process to establish tokens, and I still have the same message.

**Comment by pnbruckner** [comment]
Have you tried version 1.3.3?

**Comment by pnbruckner** [comment]
@ntbritton please provide an update.
