### ISSUE TITLE
The action `homeassistant.update_entity` doesn't force a location refresh. Any other way to force a location refresh on a particular account?

### ISSUE THREAD

**Issue by varenc** [pnbruckner/ha-google-maps#36]
I love this integration! Thanks for creating it.

Re: refreshing, I'm conservatively putting the auto refresh time to something small like 60 minutes. However sometimes I'd like to automate manually refreshing. For example if it looks like someone is approach home I'd like to trigger more frequent refreshes to zero in on their arrival time. I was hoping that the `homeassistant.update_entity` action on the ha-google-maps create `device_tracker.google_maps_.....` entity would do this but no luck.  Any other way to trigger a location update for a specific account?

sidenote: do people experience any downsides to just using very frequent refresh times? I'd be concerned Google is more likely to notice this odd behavior, and also I believe that location refreshes can cause slightly more battery drain on the user, since in some circumstance it wakes up the app on the phone and asks for an update.

**Comment by pnbruckner** [comment]
> I love this integration! Thanks for creating it.

Well, I didn't originally create the integration. I just enhanced the standard, built-in integration that has been around for a long time.

First and foremost, (to my knowledge) the API this integration uses is not documented and is probably not supported. This integration (and the built-in one it is derived from), is based on reverse engineering. Specifically, it pretends to be a web browser.

The integration's update period, which the user can specify, determines how often the integration queries the server. How often the server queries the device, and/or how often the device updates the server, is different. I honestly have no idea if there is any interaction between these events. (Specifically, I have no idea if the period the integration queries the server has any effect on how often the server gets updates from the device or devices.)

This integration has been in use for quite some time by many people. So far, I am not aware that Google has noticed or cares.

But to get to your core question, again, there are two events. First, the device has to update the server, and second, the integration has to get the latest available data from the server. The integration's update period, and/or the `homeassistant.update_entity` action, just controls the second event. I am not aware of any way to control when the first event happens.

**Comment by varenc** [comment]
Thanks for all the context! 

Is running `homeassistant.update_entity` supposed to fetch the latest location information on the user from Google's server? I found that after calling the action `homeassistant.update_entity` on my ha-google-maps entity  `device_tracker.google_maps_`, there was no update in the last_changed, last_updated, or last_reported value on the target entity. I would think that if the user's location the server is stale that actual location/address wouldn't change, but the `last_updated` time would at least. So `homeassistant.update_entity` seemed to have no effect.

 hat said I'm also currently battling a cookie expiration issue (where [this info](https://github.com/pnbruckner/ha-google-maps?tab=readme-ov-file#troubleshooting) from you is quite helpful) so perhaps that is supposed to work and I'm just having problems.  tl;dr; I think I need to move to "Alt acct only" strategy.  One that's fixed I'll be able to test more thoroughly. 

re: how Google Maps location sharing effects devices. I've learned a bit about this on iOS. I know when you use the built in Google Maps iOS integration and tap "[Refresh](https://i.imgur.com/dw1IvmH.jpeg)" on a user's location, it does indeed sometime cause the app on the user's device to silently wake up to report its current location.  I've monitored the iOS logs and have seen it happen. When exactly it does this and how often is unclear though and probably subjects to limits in place by Google and iOS. (like I don't believe it happens when a device is in "Low Power Mode").  But I have no idea if the private API this integration is using triggers the same Refresh behavior, and even if it did, I suspect the power usage would be quite minimal. (even without anyone clicking "Refresh" I've observed that the Google Maps iOS app wakes up to report its location quite frequently).

**Comment by pnbruckner** [comment]
> Is running `homeassistant.update_entity` supposed to fetch the latest location information on the user from Google's server?

Yes. Not only is it supposed to, it does. 😄 

> I found that after calling the action `homeassistant.update_entity` on my ha-google-maps entity `device_tracker.google_maps_...`, there was no update in the last_changed, last_updated, or last_reported value on the target entity. I would think that even if the user's location on the Google server is stale and the location/address don't change, at least `last_updated` time still would. So `homeassistant.update_entity` seemed to have no effect?

It is very possible there will be no change in `last_changed` and `last_updated`. However, there will always be a change in `last_reported`. You just have to be careful how you look at `last_reported`. E.g., if you are looking on the Developer Tools -> Template page, it will not update even when it changes. You have to force a browser refresh to see the change (unlike for `last_changed` & `last_updated`, which _will_ update in the browser when they change.) That seems like a deficiency in the frontend, or maybe they do that on purpose. I don't know.

Regarding refreshing the device, the same function is available on the Android Google Maps app, although it does not appear to be available from a Google Maps page in a web browser. The integration does not use a "private API". It was reverse engineered, probably by monitoring the requests sent from the Google Maps page in a web browser. And since the refresh function does not appear to be implemented in the web page, I wouldn't know how to go about discovering what the request looks like to simulate it from the integration. It would probably take capturing network traffic from the Android or iOS app, which I don't know how to do.

**Comment by varenc** [comment]
thank you! That confirms it was just a cookie invalidation issue that was confusing my while testing... thanks for taking the time.

re:
> The integration does not use a "private API".

By "private API" I just mean and API not created by Google for developers to use with all the accompanying document, including reverse engineered ones, etc. Anything that requires I feed a copy-pasted cookies from a browser is a "private API" by my definition at least.
