### ISSUE TITLE
Own avatar Image doesn't show

### ISSUE THREAD

**Issue by four2six** [pnbruckner/ha-google-maps#4]
The Google avatar image of the owner of the linked account isn't shown in the maps, despite those of the shared accounts does show. Instead it show "GM" plus the first letter of the owner's account email. 
Maybe that's just me?

**Comment by pnbruckner** [comment]
That is part of the "missing data" that the docs talk about when you have the integration create a tracker entity for the registered/added account. If you want to see the avatar, AKA entity picture, for that account, then you need to use one of the other "account strategies". See the section in the docs labeled "Account Strategies" for more information and suggestions.

**Comment by pnbruckner** [comment]
Yeah, I should add details of what data is missing, but I can tell you it is _not_ the location data. And, AFAIK, the location data for the "account holder" is no slower than the shared accounts, at least not systematically. If it's slower, then that has more to do with the device, its GPS/network access, etc.

I should also add a clear definition of what I mean by "HA only acct" in the docs.

**Comment by pnbruckner** [comment]
@four2six I updated README.md per the discussion above. Could you check it out and let me know if you think it's better, or still needs some work?

**Comment by four2six** [comment]
@pnbruckner that's much better. I'm not sure if everyone (including me) understands what 'Legacy Trackers' are and why or why not one should remove them.

**Comment by pnbruckner** [comment]
I just added "Entity-Based Instead of Legacy" to the new features list. Hopefully that sufficiently explains what "legacy" means in this context.
